name: UI test

on:
  push:
    branches: [Testing]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
        
      - name: Run Cypress UI test
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run
          browser: chrome